export const Elements = [
  { type: "textField", label: "Short Text", icon: "fluent:text-16-filled" },
  { type: "longText", label: "Long Text", icon: "dashicons:text" },
  { type: "selectField", label: "Select List", icon: "tabler:select" },
  { type: "multiSelect", label: "MultiSelect", icon: "fluent-mdl2:multi-select" },
  { type: "numberField", label: "Number", icon: "octicon:number-16" },
  { type: "date", label: "Date", icon: "bx:calendar" },
  { type: "password", label: "Password", icon: "ic:round-password" },
  { type: "checkbox", label: "Checkbox", icon: "mingcute:checkbox-line" },
  { type: "radio", label: "Radio select", icon: "ri:checkbox-circle-line" },
  { type: "email", label: "Email", icon: "mdi:email-outline" },
  { type: "file", label: "File Attachment", icon: "ion:attach-sharp" },
  { type: "grid", label: "Grid", icon: "cuida:grid-outline" },
  { type: "section", label: "Section", icon: "stash:section-divider" },
];