import { Routes, Route } from "react-router";
import { Toaster } from "sonner";
import BulderPage from "./pages/builder";
import ViewerPage from "./pages/viewer";
import "./assets/scss/style.scss";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const answerData = []

const questionDa = [
  {
    title: "Request for Quote",
    description: "",
    id: "f621832a-500f-4328-a4f7-1c689204f0e7",
    questionData: [
      {
        required: false,
        description: "Mandatory",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Service Required",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "Credit", value: "CR", id: "" },
          {
            label: "Logistics",
            value: "LOG",
            id: "9699b8ad-1e36-4d4d-be62-58c48107b5c0",
          },
          {
            label: "Marketplace",
            value: "MK",
            id: "0a464925-5811-457c-8b88-3704c961f77c",
          },
          {
            label: "Marketplace \u0026 Credit",
            value: "MKC",
            id: "2fea0151-3ccb-4cb7-ba41-49c75417d168",
          },
          {
            label: "Marketplace \u0026 Logistics",
            value: "MKL",
            id: "ccaf3ae1-94d2-4850-86a5-2ee3191153c5",
          },
          {
            label: "Marketplace, Logistics \u0026 Credit",
            value: "MLCR",
            id: "e6560eb6-2bfb-4fd5-84bd-2f5149728c1b",
          },
          {
            label: "Logistics \u0026 Credit ",
            value: "LC",
            id: "2691e0fa-1248-41d0-a104-5a5204643a72",
          },
          {
            label: "Cross border Payment",
            value: "CBP",
            id: "b1007393-8819-4d1f-85db-99f99c480ed4",
          },
          {
            label: "Sample ",
            value: "SAM",
            id: "7a4190dc-7259-4fb4-a3f2-386413550099",
          },
        ],
        id: "bfe242fc-d8ef-4fce-8d7c-1320b99bfae0",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "Mandatory",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Request Channel",
        inputType: "select",
        selectType: "list",
        options: [
          {
            label: "Referrals/Word of Mouth",
            value: "WOM",
            id: "e91912a2-6bc0-479e-8341-dd34c7417119",
          },
          {
            label: "Internal Sales Team",
            value: "SALES",
            id: "bdb6bd16-289e-497b-b1a6-7dae051ecb24",
          },
          {
            label: "External Events ",
            value: "EVN",
            id: "dbb1a3d8-4f61-4883-a335-bde287b2ab39",
          },
          {
            label: "Social Media",
            value: "SM",
            id: "d96f6fcd-ce62-4161-8fd7-4fe3c84bb4ec",
          },
        ],
        id: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "Mandatory for SM Channels",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
            value: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
            label: "Request Channel",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "SM",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Social Media Channels",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "LinkedIn", value: "1", id: "" },
          {
            label: "Instagram",
            value: "2",
            id: "3c587317-5f1d-4db5-9ee3-745e223c3048",
          },
          {
            label: "X",
            value: "3",
            id: "5e387e0a-7a56-435d-b4ca-f8ff33a37c3d",
          },
          {
            label: "Email",
            value: "4",
            id: "793c9622-ddce-4de1-ba04-b3cb2f8ef4a0",
          },
          {
            label: "TikTok",
            value: "5",
            id: "4b5aa0e4-21bf-41d6-a897-5e484c16a22b",
          },
          {
            label: "WhatsApp",
            value: "6",
            id: "e8a28748-b603-410d-851a-bf7df7eaafae",
          },
          {
            label: "Youtube",
            value: "7",
            id: "5f2742dc-a7b7-4a61-ad43-f3d4cdde4f8c",
          },
          {
            label: "Facebook",
            value: "8",
            id: "9c1d873b-efa8-493e-ad12-0d9a18dab8e7",
          },
        ],
        id: "4f0bf416-1212-48cb-b730-891655492ec2",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
            value: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
            label: "Request Channel",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "SALES",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Requester\u0027s Name",
        inputType: "text",
        id: "cb0659e3-6c4b-4bb1-983a-e0da9724a14a",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Mandatory - Legal Entity Name ",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Business Name",
        inputType: "text",
        id: "4f8e10d1-32c0-4ed2-98ba-131dac71cc39",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
            value: "25ca5987-eaf5-4ccf-826f-549c7d5d694c",
            label: "Request Channel",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "SM",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: " Contact Person Name",
        inputType: "text",
        id: "961a1c15-fffc-46c4-8bb1-1b486a0e30a8",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "961a1c15-fffc-46c4-8bb1-1b486a0e30a8",
            value: "961a1c15-fffc-46c4-8bb1-1b486a0e30a8",
            label: " Contact Person Name",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "",
          },
          {
            id: "4f0bf416-1212-48cb-b730-891655492ec2",
            value: "4f0bf416-1212-48cb-b730-891655492ec2",
            label: "Social Media Channels",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "SM",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Number Only",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "numberField",
        label: "Number",
        icon: "octicon:number-16",
        inputLabel: "Phone Number",
        inputType: "number",
        inputMode: "decimal",
        id: "f2bcc6f0-d018-4aa4-b0fa-31cc9933df1e",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description:
          "This is the exact location where the chemical will be delivered - Number, Street Name, City, State/Province and Country",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Mandatory",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Delivery Address",
        inputType: "text",
        id: "95970b55-793f-4cb5-ae43-55c70f09a0fd",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "Mandatory",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Account Status",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "New", value: "NW", id: "" },
          {
            label: "Repeat",
            value: "RPT",
            id: "6d4ac1f1-6acc-4c5b-8992-a6f64558fc78",
          },
        ],
        id: "6bfc1cdb-e359-4ccf-b5ad-85fb09102528",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Vertical - Customer Industry",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "Home \u0026 Personal Care", value: "HPC", id: "" },
          {
            label: "Food \u0026 Beverages",
            value: "FB",
            id: "5930e553-e3df-467a-92d5-cc05f09e3599",
          },
          {
            label: "Paints \u0026 Coatings",
            value: "PNT",
            id: "6a33eea6-15d5-4339-a361-a7e7ca7b5f60",
          },
          {
            label: "Pharmaceuticals",
            value: "PHC",
            id: "409aa24e-3114-42cb-a6f7-29cc74cda5ff",
          },
          {
            label: "Others",
            value: "Others",
            id: "0a0f59c7-3c6d-4142-af0b-458b498048cc",
          },
          {
            label: "Agro-Commodities",
            value: "Agro",
            id: "68f2eb83-ef9d-4e9f-8850-3094bf286034",
          },
          {
            label: "Minerals",
            value: "MIN",
            id: "a7f9c8c5-b794-4769-82f8-d23efc48223f",
          },
        ],
        id: "14819668-1f6d-47d0-a084-8ef23160336b",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "divider",
        label: "Divider",
        icon: "pixel:divider",
        inputLabel: "",
        inputType: "divider",
        id: "f87c55a2-79aa-47ea-b134-cdd4753a5a48",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
      },
      {
        required: false,
        description: "",
        value: [],
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "dataGrid",
        label: "Data Grid",
        icon: "carbon:data-table",
        inputLabel: "Product Request",
        inputType: "dataGrid",
        dataColumns: [
          {
            id: "eb3a3f28-ff98-416b-97e9-f2a532498259",
            field: "PN",
            headerName: "Product Name ",
            width: 150,
            editable: true,
            type: "text",
            validate: false,
          },
          {
            headerName: "Quantity",
            field: "QTY",
            editable: true,
            id: "e554450f-cd3f-4bfc-873b-283f01bc1d89",
            type: "number",
            validate: false,
          },
          {
            headerName: "Unit",
            field: "UNIT",
            editable: true,
            id: "82734831-868b-406a-bcec-b93ecdd45194",
            type: "text",
            validate: false,
          },
          {
            headerName: "Specification",
            field: "SPE",
            editable: true,
            id: "174a7031-c2bb-4a91-81b7-c22703da2009",
            type: "text",
            validate: false,
          },
          {
            headerName: "Certifications",
            field: "CT",
            editable: true,
            id: "a0bab40e-5fae-4c0c-88d3-045d407e2a7f",
            type: "text",
            validate: false,
          },
          {
            headerName: "Target Unit Price",
            field: "TP",
            editable: true,
            id: "140e433a-6afd-4681-9656-0ee5f7bf05b7",
            type: "text",
            validate: false,
          },
          {
            headerName: "Vendor Name",
            field: "VN",
            editable: true,
            id: "4b21b3f4-e238-4885-b418-749fd63f8654",
            type: "text",
            validate: false,
          },
          {
            headerName: "Vendor Address (Actual details))",
            field: "VA",
            editable: true,
            id: "190c27c5-247c-49a3-911d-faf77384190a",
            type: "text",
            validate: false,
          },
          {
            headerName: "Package Type ",
            field: "PT",
            editable: true,
            id: "c3d5ff09-d202-49e2-8c59-965e4e19a311",
            type: "text",
            validate: false,
          },
          {
            headerName: "Unit Size (bags, packet)",
            field: "US",
            editable: true,
            id: "e49c54ac-4f25-474d-9fe6-faf13072dac3",
            type: "text",
            validate: false,
          },
          {
            headerName: "Unit Cost Price",
            field: "CP",
            editable: true,
            id: "977346c5-0ca2-4913-8968-a4646aba7669",
            type: "text",
            validate: false,
          },
          {
            headerName: "Total Cost Price (Cash)",
            field: "TCaP",
            editable: true,
            id: "3d241d17-8fcf-417c-a78a-b3deedb9ded4",
            type: "text",
            validate: false,
          },
          {
            headerName: "Credit Days",
            field: "credit_days",
            editable: true,
            id: "9ad724cc-8645-45b0-8966-9d9ce5d63d89",
            type: "text",
            validate: false,
          },
          {
            headerName: "Unit Credit Price",
            field: "unit_credit_price",
            editable: true,
            id: "d002787c-7c92-47d4-903d-abc98da38577",
            type: "text",
            validate: false,
          },
          {
            headerName: "Total Logistics Price",
            field: "total_logistics_price",
            editable: true,
            id: "148f4341-6f58-47ab-8513-e7af0924922c",
            type: "text",
            validate: false,
          },
          {
            headerName: "Cash Cost (incl. Logistics)",
            field: "cash_cost_incl_logistics",
            editable: true,
            id: "8ee4be44-eeac-4adc-98bb-ff0ebf38a19e",
            type: "text",
            validate: false,
          },
          {
            headerName: "Credit Cost (incl. Logistics)",
            field: "credit_cost_incl_logistics",
            editable: true,
            id: "0924e62e-2899-44c4-91b8-5cbec22d6345",
            type: "text",
            validate: false,
          },
          {
            headerName: "VAT",
            field: "vat",
            editable: true,
            id: "c43a99a9-b5f8-4fbd-984f-a0eb21c515fe",
            type: "text",
            validate: false,
          },
          {
            headerName: "Commission (Optional)",
            field: "commission_optional",
            editable: true,
            id: "dff4bada-564b-446b-81e1-d6b06938eb3f",
            type: "text",
            validate: false,
          },
          {
            headerName: "Margin",
            field: "margin",
            editable: true,
            id: "eeed6a2b-6426-4410-807e-fd07cf247cef",
            type: "text",
            validate: false,
          },
          {
            headerName: "Unit Selling Price",
            field: "unit_selling_price",
            editable: true,
            id: "f13cafa4-55b9-4cbd-8acd-a049b011b6b7",
            type: "text",
            validate: false,
          },
          {
            headerName: "Total Selling Price",
            field: "total_selling_price",
            editable: true,
            id: "c4776da1-e895-4b8d-9e86-435d3161b78a",
            type: "text",
            validate: false,
          },
        ],
        id: "a0cdc8ad-9911-44c4-9218-3a4b11d19350",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Sample Required",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "Yes", value: "YS", id: "" },
          {
            label: "No",
            value: "NO",
            id: "8b444e97-2f8b-4a14-81a2-e33a20de2d6c",
          },
        ],
        id: "0751b017-1634-48ed-a216-33daed593983",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "0751b017-1634-48ed-a216-33daed593983",
            value: "0751b017-1634-48ed-a216-33daed593983",
            label: "Sample Required",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "YS",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Sample Quantity/Test Parameters",
        inputType: "text",
        id: "7f3b7934-841a-433c-b088-51a3cbaef959",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "0751b017-1634-48ed-a216-33daed593983",
            value: "0751b017-1634-48ed-a216-33daed593983",
            label: "Sample Required",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "YS",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Expected Sample Delivery Timeline",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "T\u002BSame Day", value: "TSD", id: "" },
          {
            label: "T\u002B3-5 days",
            value: "T35D",
            id: "4041d974-ac16-4feb-a446-eeebfe7c2eba",
          },
          {
            label: "T\u002B7 days",
            value: "T7D",
            id: "b22feb98-85f6-4b12-a3d9-f1b1337efb7c",
          },
          {
            label: "T\u002B15 days",
            value: "T15D",
            id: "f71a7917-135b-4787-8e93-e267961cd35c",
          },
        ],
        id: "0b3fafe9-afdb-4d50-a7a7-4ecf972c445d",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "file",
        label: "File Attachment",
        icon: "ion:attach-sharp",
        inputLabel: "Attach Documentation",
        inputType: "file",
        isMultiple: true,
        acceptedFiles: [],
        id: "e65e9ece-0f80-4f5b-9d52-8457297b8158",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "divider",
        label: "Divider",
        icon: "pixel:divider",
        inputLabel: "",
        inputType: "divider",
        id: "fed89a40-8a15-4677-ba27-f1b1c83d3670",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Logistics Services Required",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "Pick Up", value: "PK", id: "" },
          {
            label: "Delivery",
            value: "DV",
            id: "c6b1d39f-3ad3-4862-a3d9-2efdd3d5ed4d",
          },
        ],
        id: "4ad55c19-2830-4519-985e-db4e80f0dbf3",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "4ad55c19-2830-4519-985e-db4e80f0dbf3",
            value: "4ad55c19-2830-4519-985e-db4e80f0dbf3",
            label: "Logistics Service",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "DV",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Shipment Timeline (If delivery is selected)",
        inputType: "select",
        selectType: "list",
        options: [
          { label: "T\u002BSame Day", value: "TSD", id: "" },
          {
            label: "T\u002B3-5 days",
            value: "T35D",
            id: "4041d974-ac16-4feb-a446-eeebfe7c2eba",
          },
          {
            label: "T\u002B7 days",
            value: "T7D",
            id: "b22feb98-85f6-4b12-a3d9-f1b1337efb7c",
          },
          {
            label: "T\u002B15 days",
            value: "T15D",
            id: "f71a7917-135b-4787-8e93-e267961cd35c",
          },
        ],
        id: "c53090d7-26c4-4011-884c-ef2a38c93d6d",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "longText",
        label: "Long Text Field",
        icon: "dashicons:text",
        inputLabel: "Packaging Requirements",
        inputType: "text",
        id: "305512b0-7200-4e19-be20-cca33b1552e3",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "divider",
        label: "Divider",
        icon: "pixel:divider",
        inputLabel: "",
        inputType: "divider",
        id: "1e3d60a0-d011-472b-bab9-0d2cdcf367d6",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: true,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Payment Preference",
        inputType: "select",
        selectType: "list",
        options: [
          {
            label: "Cash on Delivery",
            value: "COD",
            id: "c6b1d39f-3ad3-4862-a3d9-2efdd3d5ed4d",
          },
          {
            label: "Cheque on Delivery",
            value: "CHQ",
            id: "e0b03eb7-874c-49ba-9957-7b1967b248ac",
          },
          {
            label: "Credit - 7 days",
            value: "CRD",
            id: "b4c6f579-7e93-4c8e-bbfe-bf5c40a079cc",
          },
          {
            label: "Credit - 15 days",
            value: "CR15",
            id: "56aa9205-ae22-4c26-a19b-3da20d23449f",
          },
          {
            label: "Credit - 30 days",
            value: "CR30",
            id: "81c5c738-212d-409f-9310-bf1c51b07059",
          },
          {
            label: "Cash Advance",
            value: "CAAD",
            id: "f6d131fc-8c4d-4320-9524-0156655a6b99",
          },
        ],
        id: "ef4bd368-50b8-4513-908d-ac0bf4203f5c",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "1 -Low priority , 5 - High priority",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "rating",
        label: "Ratings",
        icon: "streamline-ultimate:rating-star-ribbon",
        inputLabel: "Priority Level",
        inputType: "rating",
        id: "cabe35be-e429-469d-8d02-b1b0e04827b6",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "longText",
        label: "Long Text Field",
        icon: "dashicons:text",
        inputLabel: "Any Additional Information",
        inputType: "text",
        id: "f93214ec-1c06-4005-927c-f152a408a4ac",
        sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
    ],
  },
  {
    title: "Credit Request",
    description:
      " (Fill only if credit is required and KYC has not been done for the client)",
    id: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
    questionData: [
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: true,
        visibilityDependentFields: [
          {
            id: "bfe242fc-d8ef-4fce-8d7c-1320b99bfae0",
            value: "bfe242fc-d8ef-4fce-8d7c-1320b99bfae0",
            label: "Service Required",
            sectionId: "f621832a-500f-4328-a4f7-1c689204f0e7",
            fieldType: "text",
            operator: "equals",
            fieldValue: "",
          },
        ],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "longText",
        label: "Long Text Field",
        icon: "dashicons:text",
        inputLabel: "Business Registration Number",
        inputType: "text",
        id: "0fa238fb-870f-4548-9dc3-2f1a7d189705",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "date",
        label: "Date",
        icon: "bx:calendar",
        inputLabel: "Date of Incorporation",
        inputType: "date",
        dateType: "custom",
        dateFormat: "dd/MM/yyyy",
        minDate: null,
        maxDate: null,
        canHaveDateRange: false,
        allowYearPicker: true,
        id: "e3a367b6-94cb-42eb-a132-8c6bee1e2953",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "longText",
        label: "Long Text Field",
        icon: "dashicons:text",
        inputLabel: "Registered Business Address ",
        inputType: "text",
        id: "a41d6905-aad6-437f-8d26-b7f1cccc20b7",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Legal Status of the Business",
        inputType: "select",
        selectType: "list",
        options: [
          {
            label: "Limited Liability (LTD)",
            value: "limited liability (ltd)",
            id: "",
          },
          {
            label: "Sole Proprietorship",
            value: "sole proprietorship",
            id: "57f5b70e-0224-4376-894c-959d65a2405b",
          },
          {
            label: "Partnership",
            value: "partnership",
            id: "90a8e388-0009-4612-a8ba-b74b889d7573",
          },
          {
            label: "Unlimited Liability (UNLTD)",
            value: "unlimited liability (unltd)",
            id: "3852982f-ad55-4d64-8cda-42758fa088d7",
          },
          {
            label: "Public Sector (Agency/MDA)",
            value: "public sector (agency/MDA)",
            id: "cd960b59-8ee9-4e4a-a8e8-ea5acd008ab5",
          },
          {
            label: "Trust",
            value: "Trust",
            id: "0b9e33c5-feb6-43c8-9c5b-7d650c904850",
          },
        ],
        id: "263d68df-cf05-41d4-be2a-f2e9d28cd1e1",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Tax Identification Number",
        inputType: "text",
        id: "f980a531-43d0-4fe5-b68f-bd8d53734952",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Official E-mail Address",
        inputType: "text",
        id: "703b1d95-f16e-41f4-bbd1-69372ab43950",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "textField",
        label: "Text Field",
        icon: "fluent:text-16-filled",
        inputLabel: "Website",
        inputType: "text",
        id: "d022f04e-f004-42ce-8f87-7bfed086addc",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: [],
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "dataGrid",
        label: "Data Grid",
        icon: "carbon:data-table",
        inputLabel: "Details of Shareholders and Directors",
        inputType: "dataGrid",
        dataColumns: [
          {
            id: "ac2e7dd9-6d1c-4c32-9e54-cd773f3cc1dc",
            field: "Full Name",
            headerName: "Full Name",
            width: 150,
            editable: true,
            type: "text",
            validate: false,
          },
          {
            headerName: "Mobile Number",
            field: "Mobile Number",
            editable: true,
            id: "88cdfe3b-afb8-4526-81cb-30f498061c5e",
            type: "text",
            validate: false,
          },
          {
            headerName: "E-mail Address",
            field: "E-mail Address",
            editable: true,
            id: "a1941808-e394-4caa-bf89-824a8b4c2b2a",
            type: "text",
            validate: false,
          },
          {
            headerName: "BVN",
            field: "BVN",
            editable: true,
            id: "636216f9-2c41-404a-8ffb-254ee812e9ed",
            type: "text",
            validate: false,
          },
          {
            headerName: "ID Type",
            field: "ID Type",
            editable: true,
            id: "aa18d1a2-b43c-41bb-914e-a0917b17f111",
            type: "text",
            validate: false,
          },
          {
            headerName: "ID Number",
            field: "ID Number",
            editable: true,
            id: "eb1103cc-30cf-4bdb-87bd-b8b0573ca893",
            type: "text",
            validate: false,
          },
          {
            headerName: "Expiry Date",
            field: "Expiry Date",
            editable: true,
            id: "e08811ac-677e-4bad-a11e-dcccf1def89e",
            type: "text",
            validate: false,
          },
          {
            headerName: "Residential Address",
            field: "Residential Address",
            editable: true,
            id: "7c4a76b9-33f9-4a0a-8b4a-d55bdb317ff2",
            type: "text",
            validate: false,
          },
          {
            headerName: "State",
            field: "State",
            editable: true,
            id: "226d8712-e727-435b-9cf9-4805f5121124",
            type: "text",
            validate: false,
          },
          {
            headerName: "Shareholder Type",
            field: "Shareholder Type",
            editable: true,
            id: "1c967487-511f-4923-8f6f-b52d53192536",
            type: "text",
            validate: false,
          },
          {
            headerName: "Shareholding %",
            field: "Shareholding %",
            editable: true,
            id: "4a827cf2-abe9-44be-bbd9-7cef531fdf36",
            type: "text",
            validate: false,
          },
        ],
        id: "6e1be8c0-615c-48dc-ac83-8cd39f9f8fe8",
        sectionId: "414a26de-3f86-47ab-9c20-bf6ee3e0448c",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
      },
    ],
    disabled: false,
    isHidden: false,
  },
  {
    title: "Logistics Team ",
    description: "To be filled by the Logistics Team only",
    id: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
    questionData: [
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "About the Route",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "longText",
        label: "Long Text Field",
        icon: "dashicons:text",
        inputLabel: "Route Verification",
        inputType: "text",
        id: "0260d06f-1335-4ea9-ac3a-e0c3d110bf57",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "file",
        label: "File Attachment",
        icon: "ion:attach-sharp",
        inputLabel: "Attach Delivery Documentations",
        inputType: "file",
        isMultiple: true,
        acceptedFiles: [
          { value: "application/pdf", label: "PDF" },
          {
            value:
              "application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain",
            label: "Word",
          },
          {
            value:
              "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            label: "Spreadsheet",
          },
          { value: "video/mp4, video/x-m4v, video/*", label: "Videos" },
          {
            value:
              "application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation",
            label: "PowerPoint",
          },
          {
            value:
              "image/jpeg, image/png, image/gif, image/webp, image/svg\u002Bxml, image/heic",
            label: "Image",
          },
        ],
        id: "8bb4eac3-cff0-489b-a57a-2f0f4ae5ee96",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "divider",
        label: "Divider",
        icon: "pixel:divider",
        inputLabel: "",
        inputType: "divider",
        id: "d334388c-bfdb-44ab-9dcf-3aedc38c236c",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
      },
      {
        required: false,
        description: "",
        value: [],
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "dataGrid",
        label: "Data Grid",
        icon: "carbon:data-table",
        inputLabel: "Trucker Details",
        inputType: "dataGrid",
        dataColumns: [
          {
            id: "97138c58-14f8-41c0-b19d-161ad4e48d11",
            field: "Type",
            headerName: "Truck Type",
            width: 150,
            editable: true,
            type: "text",
            validate: false,
          },
          {
            headerName: "Trucker Price",
            field: "Price",
            editable: true,
            id: "98877c19-9def-4d2b-8b3a-dcc54fde6a87",
            type: "text",
            validate: false,
          },
          {
            headerName: "Trucker Name",
            field: "TN",
            editable: true,
            id: "98b6b30a-eb50-43f7-adc8-4c08d89f6c4b",
            type: "text",
            validate: false,
          },
          {
            headerName: "Trucker Address",
            field: "TA",
            editable: true,
            id: "12a316b9-5df6-46fb-8bd1-b86e24a057f8",
            type: "text",
            validate: false,
          },
          {
            headerName: "Phone Number",
            field: "PN",
            editable: true,
            id: "48dbccf6-c8f4-498e-9044-29df69b17b5d",
            type: "text",
            validate: false,
          },
        ],
        id: "3782dfa8-cdf8-46d9-b8f2-efff54aea65b",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "divider",
        label: "Divider",
        icon: "pixel:divider",
        inputLabel: "",
        inputType: "divider",
        id: "c78ee79f-da4a-4f67-ab81-beb0662044ca",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "file",
        label: "File Attachment",
        icon: "ion:attach-sharp",
        inputLabel: "Custody location confirmed",
        inputType: "file",
        isMultiple: true,
        acceptedFiles: [
          { value: "application/pdf", label: "PDF" },
          {
            value:
              "application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain",
            label: "Word",
          },
          {
            value:
              "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            label: "Spreadsheet",
          },
          { value: "video/mp4, video/x-m4v, video/*", label: "Videos" },
          {
            value:
              "application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation",
            label: "PowerPoint",
          },
          {
            value:
              "image/jpeg, image/png, image/gif, image/webp, image/svg\u002Bxml, image/heic",
            label: "Image",
          },
        ],
        id: "6ddda6ab-a620-4ca4-9110-786b764efe3d",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "url",
        label: "Link",
        icon: "iconamoon:link",
        inputLabel: "Custody Location Link",
        inputType: "url",
        id: "98cae7e1-2367-4b4e-804c-8f9703b0978f",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "file",
        label: "File Attachment",
        icon: "ion:attach-sharp",
        inputLabel: "Access controls confirmed",
        inputType: "file",
        isMultiple: true,
        acceptedFiles: [
          { value: "application/pdf", label: "PDF" },
          {
            value:
              "application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain",
            label: "Word",
          },
          {
            value:
              "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            label: "Spreadsheet",
          },
          { value: "video/mp4, video/x-m4v, video/*", label: "Videos" },
          {
            value:
              "application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation",
            label: "PowerPoint",
          },
          {
            value:
              "image/jpeg, image/png, image/gif, image/webp, image/svg\u002Bxml, image/heic",
            label: "Image",
          },
        ],
        id: "6e3364ce-785c-4039-b76f-8dd7e12318e6",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "file",
        label: "File Attachment",
        icon: "ion:attach-sharp",
        inputLabel: "Custody Verified",
        inputType: "file",
        isMultiple: true,
        acceptedFiles: [
          { value: "application/pdf", label: "PDF" },
          {
            value:
              "application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain",
            label: "Word",
          },
          {
            value:
              "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            label: "Spreadsheet",
          },
          { value: "video/mp4, video/x-m4v, video/*", label: "Videos" },
          {
            value:
              "application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation",
            label: "PowerPoint",
          },
          {
            value:
              "image/jpeg, image/png, image/gif, image/webp, image/svg\u002Bxml, image/heic",
            label: "Image",
          },
        ],
        id: "7aa3e5fe-2e43-4260-a188-9c3d94d0941e",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "selectField",
        label: "Select List",
        icon: "tabler:select",
        inputLabel: "Inspection Rights",
        inputType: "select",
        selectType: "list",
        options: [
          {
            label: "Granted",
            value: "G",
            id: "de47852e-074a-49d0-8c20-ac20b3724731",
          },
          {
            label: "Limited",
            value: "L",
            id: "4c4e5138-ffa0-439a-a67f-333ba7dc80da",
          },
          {
            label: "Rejected",
            value: "R",
            id: "4a9da9fc-9611-4070-85da-0fc476acb341",
          },
        ],
        id: "3ee4e086-8967-4051-85f1-b5d45c46e9ce",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        options1: [],
        dataColumns: [],
      },
      {
        required: false,
        description: "",
        value: null,
        isReadOnly: false,
        isDisabled: false,
        isRequired: false,
        customClass: "",
        elementClass: "",
        gridPosition: null,
        gridId: null,
        isHidden: false,
        visibilityDependentFields: [],
        maxLength: null,
        minLength: null,
        placeholder: "Type here",
        requiredMessage: "Field is required",
        minLengthMessage: "",
        maxLengthMessage: "",
        type: "file",
        label: "File Attachment",
        icon: "ion:attach-sharp",
        inputLabel: "Attach Delivery Documentations",
        inputType: "file",
        isMultiple: true,
        acceptedFiles: [
          { value: "application/pdf", label: "PDF" },
          {
            value:
              "application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain",
            label: "Word",
          },
          {
            value:
              "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            label: "Spreadsheet",
          },
          { value: "video/mp4, video/x-m4v, video/*", label: "Videos" },
          {
            value:
              "application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation",
            label: "PowerPoint",
          },
          {
            value:
              "image/jpeg, image/png, image/gif, image/webp, image/svg\u002Bxml, image/heic",
            label: "Image",
          },
        ],
        id: "82219e13-9f3e-43d5-9f57-0a1958622798",
        sectionId: "bf161d4b-5bde-4690-86bd-7abbe93d86d0",
        dateType: "basic",
        selectType: "list",
        options1: [],
        options: [],
        dataColumns: [],
      },
    ],
    disabled: false,
    isHidden: true,
  },
];



function App() {
  const config = {
    buttonColor: "blue",
    loaderColor: "blue",
    elementColor: "blue",
    elementBgColor: "",
    elementBorderColor: "blue",
  };
  return (
    <>
      <Toaster position="top-right" richColors closeButton />
      <Routes>
        <Route
          path="/"
          element={
            <div className="h-screen">
              <BulderPage
                onSubmit={function (e: any): void {
                  console.log(e);
                }}
                onPublish={function (e: any): void {
                  console.log(e);
                }}
                questionData={questionDa}
                config={config}
                title="Form Title"
                goBackUrl={() => undefined}
              />
            </div>
          }
        />
        <Route
          path="/viewer"
          element={
            <ViewerPage
              onSubmit={function (e: any): void {
                console.log(e);
              }}
              answerData={answerData}
              form_data={questionDa}
              config={config}
              loading={false}
              renderType={"multi"}
              onGetValues={(val: any) => {
                console.log(val);
              }}
              isReadOnly
            >
              {/* <div className="text-center w-full">
                <p>This is a child component</p>
              </div> */}
            </ViewerPage>
          }
        />
      </Routes>
    </>
  );
}

export default App;
