# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- run: npm ci
    - run: npm install -f
    - run: npm run build --if-present
    #- run: npm test

    - name: Archive production artifacts (Windows)
      run: |
            xcopy C:\Mattapedia-frontend-runner\_work\Dev.Mattapedia.FrontEnd\Dev.Mattapedia.FrontEnd\.output\public C:\inetpub\wwwroot\Dev.Mattapedia.FrontEnd /E /I /Y # Adjust "public" to match your build output folder

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: deployable-package
          path: C:\build\deployable-package.zip
